/**
 * This code was generated by Builder.io.
 */
import React from "react";

import Header from "../PreLaunchHomePage/Header.jsx";
import Footer from "../PreLaunchHomePage/Footer.jsx";
import IntroSection from "./IntroSection.jsx";
import FeatureHighlights from "./FeatureHighlights.jsx";
import Partnership from "./Partnership.jsx";
import ScheduleConsultation from "./ScheduleConsultation.jsx";
import Testimonial from "./Testimonial.jsx";
import Roi from "./Roi.jsx"

function PreLaunchHomePage() {
  return (
    <div className="forEmployersLanding">
      <Header />
        <IntroSection />
        <FeatureHighlights />
        <Partnership />
        <Testimonial/>
        <Roi/>
        <ScheduleConsultation />
      <Footer />
    </div>
  );
}

export default PreLaunchHomePage;
