/**
 * This code was generated by Builder.io.
 */
import React from "react";
import forEmployersIntro from "../../images/employerIntro.svg"

function IntroSection() {
  return (
    <section className="introSection">
      <div className="introContent">
        <h1 className="introTitle">
          Empower Your Workforce with Wellness
        </h1>
        <p className="introDescription">
          Increase productivity and cut costs with a wellness benefit that sets your company apart.
        </p>
        <div className="introCta">
          <button className="joinWaitlistButton">Get Started Today</button>
        </div>
      </div>
      <img
        src={forEmployersIntro}
        alt="Infusion therapy illustration"
        className="introImage"
      />
    </section>
  );
}

export default IntroSection;
