/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Roi() {
  return (
    <>
      <section className="roi-container">
        <div className="text-container">
          <h3>The Aivy Health ROI</h3>
          <span>Cut costs and increase productivity</span>
          <p>Curious about the impact of wellness on your workplace?
            Use our ROI calculator to see the real savings Aivy Health can bring.
            Just plug in your number of employees and their average salary, and we'll do the rest.
            It’s not just about wellness—it’s about smarter business.
          </p>
        </div>
        <div className="roi-calculator">
          <h3>Number of employees</h3>
          <span>100</span>
          <input type="range" />
          <h3>Average Salary</h3>
          <span>$400000</span>
          <input type="range" />
        </div>
      </section>
      <section className="annual-savings-container">
        <h3>Your annual savings</h3>
        <div className="results">
          <div className="column-1">
            <span className="x-result">
              xxxxxx
            </span>
            <span className="result-text">
              of savings on medical cost and absenteeism
            </span>
          </div>
          <div className="column-2">
            <span className="x-result">
              xxxxxx
            </span>
            <span className="result-text">
              of productivity gained
            </span>
          </div>
          <div className="column-3">
            <span className="x-result">
              xxxxxx
            </span>
            <span className="result-text">
              full-time employee equivalents
            </span>
          </div>
        </div>
      </section>
    </>
  );
}

export default Roi;
