/**
 * This code was generated by Builder.io.
 */
import React from "react";
import AivyBig from "../../images/aivyLogoBig.svg";


function ScheduleConsultation() {
  return (
    <section className="book-consultation">
      <img src={AivyBig} alt="" />
      <h1>Schedule a Consultation</h1>
      <form className="contactForm">
        <div className="formRow">
          <input
            type="text"
            placeholder="First"
            aria-label="First Name"
            className="formInput"
          />
          <input
            type="text"
            placeholder="Last"
            aria-label="Last Name"
            className="formInput"
          />
        </div>
        <div className="formRow">
          <input
            type="email"
            placeholder="Email"
            aria-label="Email"
            className="formInput"
          />
          <input
            type="tel"
            placeholder="Phone Number"
            aria-label="Phone Number"
            className="formInput"
          />
        </div>
        <div className="formRow">
          <input
            type="text"
            placeholder="Subject: Book A Consultation"
            aria-label="Subject"
            className="formInput"
          />
        </div>
        <div className="formRow">
          <textarea
            placeholder="Join us in creating a healthier, more productive workplace with innovative, forward-thinking infusion solutions."
            aria-label="Join us in creating a healthier, more productive workplace with innovative, forward-thinking infusion solutions."
            className="formTextarea"
          ></textarea>
        </div>
        <button type="submit" className="submitButton">
          Submit
        </button>
      </form>
    </section>
  );
}

export default ScheduleConsultation;
