/**
 * This code was generated by Builder.io.
 */
import React from "react";
import AivyBig from "../../images/aivyLogoBig.svg";
import aivyTextLogo from "../../images/how-it-works-text-logo.svg";

function DemoRequest() {
  return (
    <section className="demo-request">
      <img src={AivyBig} alt="" />
      <h1>Get a demo of <img
          src={aivyTextLogo}
          alt="Aivy Health"
          className="logo-demo-request"
        /></h1>
      <form className="contactForm">
        <div className="formRow">
          <input
            type="text"
            placeholder="First"
            aria-label="First Name"
            className="formInput"
          />
          <input
            type="text"
            placeholder="Last"
            aria-label="Last Name"
            className="formInput"
          />
        </div>
        <div className="formRow">
          <input
            type="email"
            placeholder="Email"
            aria-label="Email"
            className="formInput"
          />
          <input
            type="tel"
            placeholder="Phone Number"
            aria-label="Phone Number"
            className="formInput"
          />
        </div>
        <div className="formRow">
          <input
            type="text"
            placeholder="Subject: Book A Demo"
            aria-label="Subject"
            className="formInput"
          />
        </div>
        <div className="formRow">
          <textarea
            placeholder="Find out why everyone is switching to Aivy Health."
            aria-label="Find out why everyone is switching to Aivy Health."
            className="formTextarea"
          ></textarea>
        </div>
        <button type="submit" className="submitButton">
          Submit
        </button>
      </form>
    </section>
  );
}

export default DemoRequest;
