/**
 * This code was generated by Builder.io.
 */
import React from "react";
import howItWorksGraphic from "../../images/howItWorksGraphic.svg";


function HowItWorks() {
  return (
    <section className="howItWorks forPharmacies">
      <img src={howItWorksGraphic} alt="" />
    </section>
  );
}

export default HowItWorks;
