/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PreLaunchHomePage.module.css";
import smilingNurse from '../../images/smiling_nurse_stock.png'

function CallToAction() {
  return (
    <section className={styles.callToAction}>
      <div className={styles.ctaContent}>
        <h2 className={styles.ctaTitle}>
          <span className={styles.ctaSubtitle}>WE'RE HERE FOR YOU</span>
          Book your on-demand infusion today
        </h2>
        <p className={styles.ctaDescription}>
          Curious if on-demand infusion is right for you? Message or email us at
          any time. We'll help you every step of the way.
        </p>
      </div>
      <div className={styles.flexRow}>
        {/* <img
          src={smilingNurse}
          alt=""
          className={styles.ctaBackground}
        /> */}
        <div className={styles.ctaButtons}>
          <button className={styles.appointmentButton}>
            Request An Appointment
          </button>
          <button className={styles.referralButton}>Submit A Referral</button>
        </div>
      </div>
    </section>
  );
}

export default CallToAction;
