/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PreLaunchHomePage.module.css";
import smilingNurse from '../../images/smiling_nurse_stock.png'

function CallToAction() {
  return (
    <section className="callToAction">
      <div className="ctaContent">
        <span className="ctaSubtitle">WE'RE HERE FOR YOU</span>
        <h2 className="ctaTitle">
          Book your on-demand infusion today
        </h2>
        <p className="ctaDescription">
          Curious if on-demand infusion is right for you? Message or email us at
          any time. We'll help you every step of the way.
        </p>
      </div>
      <div className="flexRow">
        {/* <img
          src={smilingNurse}
          alt=""
          className="ctaBackground}
        /> */}
        <div className="ctaButtons">
          <button className="appointmentButton">
            Request An Appointment
          </button>
          <button className="referralButton">Submit A Referral</button>
        </div>
      </div>
    </section>
  );
}

export default CallToAction;
