/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PreLaunchHomePage.module.css";

function CaseStudy() {
  return (
    <article className="caseStudy">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e4fa41bb1c1b0eaa5e0f4a48af7d9996ad52cdd67d666cc7f40b9d42620b1a69?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
        alt=""
        className="caseStudyBackground"
      />
      <div className="caseStudyContent">
        <h2 className="caseStudyTitle">Irene's Aivy Journey</h2>
        <p className="caseStudyComplaint">
          <strong>Complaint:</strong> Irene suffered from chronic migraines that
          disrupted her daily life. She needed a reliable solution to manage her
          condition effectively.
        </p>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/911a45b44478d07d558a29a1feaecf0ca61ac7a19b9b559d479892c42b030104?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
          alt=""
          className="divider"
        />
        <h3 className="interventionsTitle">Aivy Interventions:</h3>
        <ul className="interventionsList">
          <li className="interventionItem">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/98ca436776df11bfd5a6bb87c32fd9040ec02a918a6008eb19e105e13172b550?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
              alt=""
              className="interventionIcon"
            />
            <p>
              <strong>Preventive Care:</strong> Regular Vyepti infusions every 3
              months at home to prevent migraines.
            </p>
          </li>
          <li className="interventionItem">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/19b73aea1b10547d1cf07a05527ebdcc9e2a683640cc1419b6f371ed14015291?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
              alt=""
              className="interventionIcon"
            />
            <p>
              <strong>Acute Relief:</strong> On-demand migraine cocktail
              infusions to manage breakthrough migraines.
            </p>
          </li>
          <li className="interventionItem">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/cf42e1a3c977480251212d953b83278dc4d311d35018dac136e22053f114bdb0?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
              alt=""
              className="interventionIcon"
            />
            <p>
              <strong>Affordable Options:</strong> Utilized HSA/FSA funds to
              cover costs, making treatment affordable and accessible.
            </p>
          </li>
          <li className="interventionItem">
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/fc487062fa42494b0186d08b6c6d67d0b15d187192e2d38362f5ed38500d0ea5?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
              alt=""
              className="interventionIcon"
            />
            <p>
              <strong>Cost-Effective:</strong> Combining preventive and acute
              care reduced the need for expensive ER visits.
            </p>
          </li>
        </ul>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/113788d46fc61b6fc43eabfcfe66ec59a146e5e7e65f1df8075caf246f294174?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
          alt=""
          className="divider"
        />
        <p className="caseStudyOutcome">
          <strong>Outcome:</strong> Aivy Health's regular Vyepti infusions and
          on-demand migraine cocktails have significantly reduced Irene's need
          for emergency room visits, saving her both time and money while
          effectively managing her migraines.
        </p>
      </div>
    </article>
  );
}

export default CaseStudy;
