/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PreLaunchHomePage.module.css";

function ContactForm() {
  return (
    <section className={styles.contactSection}>
      <div className={styles.contactInfo}>
        <h2 className={styles.contactTitle}>Still have questions?</h2>
        <p className={styles.contactDescription}>
          Contact us to explore more ways we can help you achieve health.
        </p>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/aa27cbb0fc23678587417a6f38364ec1f5c46d3fb717b177145cffe47f75b835?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
          alt="Contact illustration"
          className={styles.contactImage}
        />
      </div>
      <form className={styles.contactForm}>
        <div className={styles.formRow}>
          <input
            type="text"
            placeholder="First"
            aria-label="First Name"
            className={styles.formInput}
          />
          <input
            type="text"
            placeholder="Last"
            aria-label="Last Name"
            className={styles.formInput}
          />
        </div>
        <div className={styles.formRow}>
          <input
            type="email"
            placeholder="Email"
            aria-label="Email"
            className={styles.formInput}
          />
          <input
            type="tel"
            placeholder="Phone Number"
            aria-label="Phone Number"
            className={styles.formInput}
          />
        </div>
        <div className={styles.formRow}>
          <input
            type="text"
            placeholder="State"
            aria-label="State"
            className={styles.formInput}
          />
          <input
            type="text"
            placeholder="Insurance Provider"
            aria-label="Insurance Provider"
            className={styles.formInput}
          />
        </div>
        <input
          type="text"
          placeholder="Subject"
          aria-label="Subject"
          className={styles.formInput}
        />
        <textarea
          placeholder="How can we help you?"
          aria-label="How can we help you?"
          className={styles.formTextarea}
        ></textarea>
        <button type="submit" className={styles.submitButton}>
          Submit
        </button>
      </form>
    </section>
  );
}

export default ContactForm;
