/**
 * This code was generated by Builder.io.
 */
import React from "react";
import searchIcon from "../../images/searchIcon.svg";
import iphone from "../../images/iphone.svg";

function EmployersCover() {
    return (
        <section className="employersCover">
            <img className="employersImage" src={iphone} />
            <div className="employersTextContainer">
                <h2>Employers cover Aivy Health</h2>
                <span>Your company may be covering the cost of Aivy Health for employees
                    and their families. Aivy Health offers personalized infusion therapy,
                    including on-demand wellness and urgent care infusions, specialty treatments, and 1:1 telehealth consultations.
                    Our services are designed to make infusion therapy easy, accessible, and personalized for every patient.
                    Search below to see if your employer covers Aivy Health.
                </span>
                <span>
                    If you don’t find your employer listed, you can sign up for a membership independently here.
                </span>
                <div className="employerSearchContainer">
                    <form className="searchForm">
                        <label htmlFor="search" className="visuallyHidden">
                            Enter your employer
                        </label>
                        <input
                            type="search"
                            id="search"
                            placeholder="Enter your employer"
                            className="searchInput"
                        />
                        <img
                            src={searchIcon}
                            alt="Search"
                            className="searchIcon"
                        />
                        <button type="submit" className="submitButton">
                            Get Started
                        </button>
                    </form>
                </div>
            </div>
        </section>
    );
}

export default EmployersCover;
