/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PreLaunchHomePage.module.css";

function FAQSection() {
  const faqs = [
    {
      question:
        "What is the difference between a wellness and specialty infusion?",
      answer: "Answer content here...",
    },
    {
      question: "How do I schedule a specialty infusion?",
      answer: "Answer content here...",
    },
    {
      question: "How do I schedule my wellness infusion?",
      answer: "Answer content here...",
    },
    {
      question:
        "Can I get both a specialty and a wellness infusion at the same time?",
      answer: "Answer content here...",
    },
    {
      question: "How long will it take to receive my infusion?",
      answer: "Answer content here...",
    },
    {
      question: "How do I prepare for my infusion?",
      answer: "Answer content here...",
    },
    {
      question:
        "I am currently getting infusions at an ambulatory clinic, infusion center, or doctor's office. How do I switch to Aivy Health?",
      answer: "Answer content here...",
    },
    {
      question: "Where can I have my appointment?",
      answer: "Answer content here...",
    },
    {
      question: "How do I pay for my bill?",
      answer: "Answer content here...",
    },
  ];

  return (
    <section className="faqSection">
      <h2 className="faqTitle">Frequently Asked Questions</h2>
      <div className="faqGrid">
        {faqs.map((faq, index) => (
          <details key={index} className="faqItem">
            <summary className="faqQuestion">{faq.question}</summary>
            <p className="faqAnswer">{faq.answer}</p>
          </details>
        ))}
      </div>
    </section>
  );
}

export default FAQSection;
