/**
 * This code was generated by Builder.io.
 */
import React from "react";


function Footer() {
  return (
    <footer className="footer">
      <div className="footerContent">
        <div className="footerMission">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ea98d19a3b228f9ba2bfaf591ca10cbd41b1b8b727c85966a9fdc8b9abbd1696?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
            alt="Aivy Health Logo"
            className="footerLogo"
          />
          <div className="missionStatement">
            <h3 className="missionTitle">Our Mission</h3>
            <p className="missionDescription">
              Committed to making infusion therapy easy, accessible, and
              personalized for every patient.
            </p>
          </div>
        </div>
        <nav className="footerNav">
          <div className="footerNavColumn">
            <h4 className="footerNavTitle">The Company</h4>
            <ul className="footerNavList">
              <li>
                <a href="#features">Features</a>
              </li>
              <li>
                <a href="#about">About</a>
              </li>
              <li>
                <a href="#pharmacies">For Pharmacies</a>
              </li>
              <li>
                <a href="#employers">For Employers</a>
              </li>
              <li>
                <a href="#careers">Careers</a>
              </li>
            </ul>
          </div>
          <div className="footerNavColumn">
            <h4 className="footerNavTitle">Blog</h4>
            <ul className="footerNavList">
              <li>
                <a href="#news">News</a>
              </li>
              <li>
                <a href="#press">Press</a>
              </li>
              <li>
                <a href="#guides">Guides</a>
              </li>
            </ul>
          </div>
          <div className="footerNavColumn">
            <h4 className="footerNavTitle">Getting Started</h4>
            <ul className="footerNavList">
              <li>
                <a href="#faq">FAQ</a>
              </li>
              <li>
                <a href="#membership">Membership Plan</a>
              </li>
              <li>
                <a href="#refer">Refer A Friend</a>
              </li>
              <li>
                <a href="#support">Support Center</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
      <div className="footerBottom">
        <p className="copyright">
          © 2024 Aivy Health. All rights reserved.
        </p>
        <div className="legalLinks">
          <a href="#privacy" className="legalLink">
            Privacy Policy
          </a>
          <a href="#terms" className="legalLink">
            Terms of Service
          </a>
        </div>
      </div>
    </footer>
  );
}

export default Footer;
