/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PreLaunchHomePage.module.css";

function Footer() {
  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <div className={styles.footerMission}>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ea98d19a3b228f9ba2bfaf591ca10cbd41b1b8b727c85966a9fdc8b9abbd1696?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
            alt="Aivy Health Logo"
            className={styles.footerLogo}
          />
          <div className={styles.missionStatement}>
            <h3 className={styles.missionTitle}>Our Mission</h3>
            <p className={styles.missionDescription}>
              Committed to making infusion therapy easy, accessible, and
              personalized for every patient.
            </p>
          </div>
        </div>
        <nav className={styles.footerNav}>
          <div className={styles.footerNavColumn}>
            <h4 className={styles.footerNavTitle}>The Company</h4>
            <ul className={styles.footerNavList}>
              <li>
                <a href="#features">Features</a>
              </li>
              <li>
                <a href="#about">About</a>
              </li>
              <li>
                <a href="#pharmacies">For Pharmacies</a>
              </li>
              <li>
                <a href="#employers">For Employers</a>
              </li>
              <li>
                <a href="#careers">Careers</a>
              </li>
            </ul>
          </div>
          <div className={styles.footerNavColumn}>
            <h4 className={styles.footerNavTitle}>Blog</h4>
            <ul className={styles.footerNavList}>
              <li>
                <a href="#news">News</a>
              </li>
              <li>
                <a href="#press">Press</a>
              </li>
              <li>
                <a href="#guides">Guides</a>
              </li>
            </ul>
          </div>
          <div className={styles.footerNavColumn}>
            <h4 className={styles.footerNavTitle}>Getting Started</h4>
            <ul className={styles.footerNavList}>
              <li>
                <a href="#faq">FAQ</a>
              </li>
              <li>
                <a href="#membership">Membership Plan</a>
              </li>
              <li>
                <a href="#refer">Refer A Friend</a>
              </li>
              <li>
                <a href="#support">Support Center</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
      <div className={styles.footerBottom}>
        <p className={styles.copyright}>
          © 2024 Aivy Health. All rights reserved.
        </p>
        <div className={styles.legalLinks}>
          <a href="#privacy" className={styles.legalLink}>
            Privacy Policy
          </a>
          <a href="#terms" className={styles.legalLink}>
            Terms of Service
          </a>
        </div>
      </div>
    </footer>
  );
}

export default Footer;
