/**
 * This code was generated by Builder.io.
 */
import React from "react";
import searchIcon from "../../images/searchIcon.svg";
import profileIcon from "../../images/profile-icon.svg";
import HamburgerMenu from "./HamburgerMenu";
import { HashLink } from 'react-router-hash-link';
import aivyTextLogo from "../../images/aivy-header-text-logo.svg"

function Header() {
  return (
    <header className="header">
      <div className="topMenu">
        {/* todo: add back login and appointmentButton post launch */}
        {/* <div className="login">Login</div> */}
        <button className="joinButton" href="https://forms.gle/your-google-form-link" target="_blank">Join the waitlist</button>
        {/* <button className="appointmentButton">
          Request an Appointment
        </button> */}
      </div>
      <HamburgerMenu />
      <nav className="mainNav">
        <ul className="navList">
          <li>
            <a href="/" className="navLink">
              For Patients
            </a>
          </li>
          <li>
            <a href="/pharmacies" className="navLink">
              For Pharmacies
            </a>
          </li>
          <li>
            <a href="/employers" className="navLink">
              For Employers
            </a>
          </li>
          {/* todo: add providers landing */}
          {/* <li>
            <a href="#providers" className="navLink">
              For Providers
            </a>
          </li> */}
        </ul>
        <img
          src={aivyTextLogo}
          alt="Aivy Health"
          className="logo"
        />
        {/* <h1 className="logo">AivyHealth</h1> */}
        <div className="rightContainer">
          <ul className="navList">
            <li>
              <HashLink to="/patients#faqSection" className="navLink">
                FAQs
              </HashLink>
            </li>
            {/* todo: add back forms postlaunch */}
            {/* <li>
              <a href="#forms" className="navLink">
                Forms
              </a>
            </li> */}
          </ul>
          <form className="searchForm">
            <label htmlFor="search" className="visuallyHidden">
              Search
            </label>
            <input
              type="search"
              id="search"
              placeholder="Search"
              className="searchInput"
            />
            <button type="submit" className="searchButton">
              <img
                src={searchIcon}
                alt="Search"
                className="searchIcon"
              />
            </button>
          </form>
          <img
            src={profileIcon}
            alt="User Profile"
            className="profileIcon"
          />
        </div>
      </nav>
    </header>
  );
}

export default Header;
