/**
 * This code was generated by Builder.io.
 */
import React from "react";


function Header() {
  return (
    <header className="header">
      <div className="topMenu">
        {/* todo: add back login and appointmentButton post launch */}
        {/* <div className="login">Login</div> */}
        <button className="joinButton">Join the waitlist</button>
        {/* <button className="appointmentButton">
          Request an Appointment
        </button> */}
      </div>
      <nav className="mainNav">
        <ul className="navList">
          <li>
            <a href="#patients" className="navLink">
              For Patients
            </a>
          </li>
          <li>
            <a href="#pharmacies" className="navLink">
              For Pharmacies
            </a>
          </li>
          <li>
            <a href="#employers" className="navLink">
              For Employers
            </a>
          </li>
          <li>
            <a href="#providers" className="navLink">
              For Providers
            </a>
          </li>
        </ul>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/479e72cf12503a2f4604c9b0be9eb4bc9f8afa062ae61bc02f2fedd8f30387e5?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
          alt="Aivy Health Logo"
          className="logo"
        />
        <div className="rightContainer">
          <ul className="navList">
            <li>
              <a href="#faqs" className="navLink">
                FAQs
              </a>
            </li>
            {/* todo: add back forms postlaunch */}
            {/* <li>
              <a href="#forms" className="navLink">
                Forms
              </a>
            </li> */}
          </ul>
          <form className="searchForm">
            <label htmlFor="search" className="visuallyHidden">
              Search
            </label>
            <input
              type="search"
              id="search"
              placeholder="Search"
              className="searchInput"
            />
            <button type="submit" className="searchButton">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/c0bfde7a-ecfd-4bf6-8547-d6e222660177?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
                alt="Search"
                className="searchIcon"
              />
            </button>
          </form>
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ceff5ca879f44c414c22fb2e41208547f876e3d24ca9f49aadf357dd6c0b9a53?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
            alt="User Profile"
            className="profileIcon"
          />
        </div>
      </nav>
    </header>
  );
}

export default Header;
