/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PreLaunchHomePage.module.css";

function IntroSection() {
  return (
    <section className={styles.introSection}>
      <div className={styles.introContent}>
        <h1 className={styles.introTitle}>
          On-demand infusions for a healthier you
        </h1>
        <p className={styles.introDescription}>
          We integrate wellness and specialty infusions into one service. Our
          approach increases access to necessary treatments, significantly
          reduces patient wait times, and offers a more efficient,
          patient-centric solution.
        </p>
        <div className={styles.introCta}>
          <button className={styles.treatmentButton}>What we treat</button>
          <button className={styles.coverageButton}>
            See if you're covered
          </button>
        </div>
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/480d9f4c4ec45acd5ae48b0695be31b145af8687588a5dfda8506084efa796db?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
        alt="Infusion therapy illustration"
        className={styles.introImage}
      />
    </section>
  );
}

export default IntroSection;
