/**
 * This code was generated by Builder.io.
 */
import React from "react";


function IntroSection() {
  return (
    <section className="introSection">
      <div className="introContent">
        <h1 className="introTitle">
          On-demand infusions for a healthier you
        </h1>
        <p className="introDescription">
          We integrate wellness and specialty infusions into one service. Our
          approach increases access to necessary treatments, significantly
          reduces patient wait times, and offers a more efficient,
          patient-centric solution.
        </p>
        <div className="introCta">
          <button className="joinWaitlistButton">Join the waitlist</button>
          <button className="treatmentButton">
            What we treat
          </button>
        </div>
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/480d9f4c4ec45acd5ae48b0695be31b145af8687588a5dfda8506084efa796db?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
        alt="Infusion therapy illustration"
        className="introImage"
      />
    </section>
  );
}

export default IntroSection;
