/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PreLaunchHomePage.module.css";
import Header from "./Header";
import IntroSection from "./IntroSection";
import CaseStudy from "./CaseStudy";
import HowItWorks from "./HowItWorks";
import WaitlistSection from "./WaitlistSection";
import FeatureHighlights from "./FeatureHighlights";
import Testimonial from "./Testimonial";
import TreatmentOptions from "./TreatmentOptions";
import CallToAction from "./CallToAction";
import FAQSection from "./FAQSection";
import ContactForm from "./ContactForm";
import Footer from "./Footer";

function PreLaunchHomePage() {
  return (
    <div className={styles.preLaunchHomePage}>
      <Header />
      <IntroSection />
      <section className={styles.caseStudySection}>
        <CaseStudy />
        <HowItWorks />
      </section>
      <WaitlistSection />
      <FeatureHighlights />
      <Testimonial />
      <TreatmentOptions />
      <CallToAction />
      <FAQSection />
      <ContactForm />
      <Footer />
    </div>
  );
}

export default PreLaunchHomePage;
