/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PreLaunchHomePage.module.css";

function Testimonial() {
  return (
    <section className="testimonial">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/3e7ea82ed723c22f25ab1e7cf84a3c1095e799e548810f3e1aed409ef9dfd550?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
        alt=""
        className="testimonialQuote"
      />
      <blockquote className="testimonialText">
        " Knowing that I can get my Remicade and essential vitamins quickly from
        a trusted nurse, without leaving home, has made such a difference during
        my Crohn's flare-ups. It's the care I need, exactly when I need it. "
      </blockquote>
      <footer className="testimonialAuthor">Kenji Y.</footer>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a752f202f5bfc9fd79921387fe05687bcdf21776c19e1928dc0604b172176639?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
        alt="Portrait of Kenji Y."
        className="testimonialImage"
      />
    </section>
  );
}

export default Testimonial;
