/**
 * This code was generated by Builder.io.
 */
import React from "react";


function WaitlistSection() {
  return (
    <section className="waitlistSection">
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d19cb20cceaae7447ed333f8caf43d34ab477678f8af10ebacefe7eb11fdd44b?placeholderIfAbsent=true&apiKey=03b8c186f0974d22b1cfe3aef28c106c"
        alt=""
        className="waitlistBackground"
      />
      <div className="waitlistContent">
        <h2 className="waitlistTitle">Join our waitlist</h2>
        <p className="waitlistDescription">
          Receive latest infusion news, health tips, and exclusive offers
          straight to your inbox.
        </p>
        <form className="waitlistForm">
          <label htmlFor="email" className="visuallyHidden">
            Email address
          </label>
          <input
            type="email"
            id="email"
            placeholder="Enter your email address..."
            className="emailInput"
            aria-label="Enter your email address"
          />
          <button type="submit" className="submitButton">
            Send
          </button>
        </form>
      </div>
    </section>
  );
}

export default WaitlistSection;
