/**
 * This code was generated by Builder.io.
 */
import React from "react";

function WhatWeTreat() {
  // var i = 0;
  // var txt = 'Lorem ipsum typing effect!'; /* The text */
  // var speed = 50; /* The speed/duration of the effect in milliseconds */

  // function typeWriter() {
  //   if (i < txt.length && document.getElementById("typeWriter")) {
  //     document.getElementById("typeWriter").innerHTML += txt.charAt(i);
  //     i++;
  //     setTimeout(typeWriter, speed);
  //   }
  // }

  React.useEffect(() => {
    var phrases = [
      'Health & Wellness',
      'Urgent care symptoms',
      'Neurological conditions',
      'Infections',
      'Autoimmune diseases',
      'Bleeding disorders',
      'Chronic inflammation',
      'Women’s health'
    ];
    var i = 0;
    var phrasesIndex = 0;
    var txt = phrases[phrasesIndex];
    var speed = 200;
    function typeWriter() {
      if (i < txt.length) {
        document.getElementById("typeWriter").innerHTML += txt.charAt(i);
        i++;
        setTimeout(typeWriter, speed);
      } else if (phrasesIndex < phrases.length - 1) {
        document.getElementById("typeWriter").innerHTML = '';
        i = 0;
        phrasesIndex++;
        txt = phrases[phrasesIndex];
        setTimeout(typeWriter, speed);
      } else if (phrasesIndex === phrases.length - 1) {
        document.getElementById("typeWriter").innerHTML = '';
        i = 0;
        phrasesIndex = 0;
        txt = phrases[phrasesIndex];
        setTimeout(typeWriter, speed);
      }
    }

    typeWriter();
  }, []);
  
  return (
    <section className="whatWeTreat">
      <div className="whatWeTreatContainer">
        <span>What we treat:</span>
        <p className="typeWriter" id="typeWriter"></p>
      </div>
    </section>
  );
}

export default WhatWeTreat;
